# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='blocker_type',
            field=models.CharField(choices=[('none', 'No Blocker'), ('free_snooze', 'Free Snooze'), ('costly_snooze', 'Costly Snooze')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='participant',
            name='receives_subsidy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='snooze_delay',
            field=models.IntegerField(default=0),
        ),
    ]
