# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0002_auto_20190319_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='treatment_active',
            field=models.BooleanField(default=False),
        ),
    ]
