# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0003_participant_treatment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('receives_subsidy', models.BooleanField(default=True)),
                ('blocker_type', models.CharField(choices=[('none', 'No Blocker'), ('free_snooze', 'Free Snooze'), ('costly_snooze', 'Costly Snooze')], default='none', max_length=32)),
                ('snooze_delay', models.IntegerField(default=0)),
                ('treatment_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='blocker_type',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='receives_subsidy',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='snooze_delay',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='treatment_active',
        ),
        migrations.AddField(
            model_name='treatmentphase',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='study_support.Participant'),
        ),
    ]
