# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0005_auto_20190419_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentphase',
            name='initial_snooze_amount',
            field=models.FloatField(default=10),
        ),
    ]
