# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0006_treatmentphase_initial_snooze_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='metadata',
            field=models.TextField(default='{}', max_length=1048576),
        ),
    ]
