# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0007_participant_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField()),
                ('version_name', models.CharField(max_length=32)),
                ('version_code', models.IntegerField()),
                ('download_url', models.URLField(max_length=512)),
                ('release_notes', models.TextField(max_length=4096)),
            ],
        ),
    ]
