# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0009_participant_performance_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='performance_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
