# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0010_auto_20190801_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentphase',
            name='blocker_type',
            field=models.CharField(choices=[('none', 'No Blocker'), ('free_snooze', 'Free Snooze'), ('costly_snooze', 'Costly Snooze'), ('no_snooze', 'No Snooze')], default='none', max_length=32),
        ),
    ]
