# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0015_auto_20190819_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024, unique=True)),
                ('claimed', models.BooleanField(default=False)),
                ('configuration', models.TextField(max_length=1048576)),
            ],
        ),
    ]
