# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0016_appcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcode',
            name='claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
