# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0017_appcode_claim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
