# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0018_participant_email_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPacageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_package', models.CharField(max_length=512)),
                ('replacement_package', models.CharField(blank=True, max_length=512, null=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
        ),
    ]
