# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-06 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0019_apppacageinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppPacageInfo',
            new_name='AppPackageInfo',
        ),
    ]
