# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0021_appcode_generate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email_address',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
