# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_support', '0023_auto_20200327_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentphase',
            name='blocker_type',
            field=models.CharField(choices=[('none', 'No Blocker'), ('free_snooze', 'Free Snooze'), ('costly_snooze', 'Costly Snooze'), ('flexible_snooze', 'Flexible Snooze'), ('no_snooze', 'No Snooze')], default='none', max_length=32),
        ),
    ]
