"""
Django settings for phone_dashboard project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'sorl.thumbnail',
    'prettyjson',
    'study_support',
    'passive_data_kit',
    'nagios_monitor',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'phone_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'phone_dashboard.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

USE_I18N = True
USE_L10N = True
USE_TZ = True

PDK_CUSTOM_NAV_ITEMS = ({
    'title': 'Treatments',
    'url': '/study/treatment-phases'
},)

PDK_DEFAULT_GROUP_NAME = '0. Phone Dashboard Participants'

PDK_EXTRA_GENERATORS = (
    ('nyu-full-export', 'NYU Pilot Aggregated Phone Usage',),
    ('nyu-daily-usage-summary', 'NYU Daily App Usage Summary',),
    ('nyu-app-budgets', 'NYU App Budgets',),
    ('nyu-snooze-costs', 'NYU Snooze Costs',),
#    ('nyu-snooze-events', 'NYU Snooze Events',),
    ('nyu-snooze-warnings', 'NYU Snooze Warning Events'),
    ('nyu-participant-status', 'NYU Participant Statuses'),
    ('nyu-violator-usage', 'NYU Violator App Usage'),
    ('nyu-participant-opt-out', 'NYU Participant Opt-Out'),
    ('nyu-latest-usage-summaries', 'NYU Latest Usage Summaries'),
    ('nyu-participants', 'NYU Participant List'),
    ('nyu-active-users', 'NYU Active Users'),
    ('nyu-snooze-delays', 'NYU Snooze Delays'),
    ('phone-dashboard-yesterday-summaries', 'Phone Dashboard Daily Summaries'),
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

from .local_settings import *
